### ISSUE TITLE
Workflow question

### ISSUE THREAD

**Issue by christophrumpel** [iboldurev/api-ai-php#1]
Hey,

thx for this package. Tested it and works great.
What I am not sure about is how the workflow should be.

In my teste I sent some text to my api.ai agent and I got some info from the json file back.
So the workflo would be:

messenger app -> sends text to my app -> I make a request to api.ai -> result from api.ai -> send back to messenger app

What I have read about api.ai it seems they use webhooks. This sounds like after using a service the result is sent back to api.ai so the workflow looks like:

messenger app -> sends text to my app -> I make a request to api.ai -> api.ai makes a call to my service (e.g get weather info) -> data gets back to api.ai -> then ?

So how do you handle webhook calls? Is that possible with your package? Am I getting this right? Was my problem clear ?=)

Thanks and greets

**Comment by iboldurev** [comment]
Hi , soon I will add examples of integration with facebook/telegram webhooks.

**Comment by christophrumpel** [comment]
Hey, no I'm not talking about the messenger site. I mean the api.ai webhooks.

When you use sthg like a weather api then the workflow could be like:

-> messager -> api.ai -> weather api service (over the api.ai webhook) -> back to api.ai -> answer message back to messenger, right?

It is different when you use a server during the conversation, when api.ai needs data from a service inside the conversation. Do you know what I mean?

**Comment by iboldurev** [comment]
Ok I understand , you need to use actionmapping.

Please read Dialog example.
https://github.com/iboldurev/api-ai-php/blob/master/README.md#dialog

**Comment by christophrumpel** [comment]
Hey thx, this could be what I want :-) I will check it. Thx a lot 👍

**Comment by iboldurev** [comment]
christophrumpel, Examples are using an old version of the library, in the readme file is an example of use. Try this implementation.
